### ISSUE TITLE
`wire-local app serve` is not working

### ISSUE THREAD

**Issue by rzadp** [dxos/cli#241]
```
DEBUG=* wire-local app serve
  pm2:paths pm2 home resolved to /Users/przemek/.pm2 /Users/przemek +0ms
  pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +0ms
  pm2:client Using RPC file /Users/przemek/.pm2/rpc.sock +0ms
  pm2:client Using PUB file /Users/przemek/.pm2/pub.sock +0ms
  interactor:client [PING INTERACTOR] Trying to connect to Interactor daemon +0ms
  axon:sock connect attempt null:/Users/przemek/.pm2/interactor.sock +0ms
  axon:sock error ENOENT +79ms
  axon:sock ignored ENOENT +0ms
  dxos:cli Error: spawn wire-app-server ENOENT
  dxos:cli     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
  dxos:cli     at onErrorNT (internal/child_process.js:467:16)
  dxos:cli     at processTicksAndRejections (internal/process/task_queues.js:82:21) +0ms

Error: spawn wire-app-server ENOENT
```

The issue can be worked around by running `yarn dx app serve` in the cli repo root.

**Comment by rzadp** [comment]
This is lower priority because it doesn't affect end users of CLI, only one use case of local development.
